name: HealPlus
main: me.flamexmystix.healplus.HealPlus
version: 1.0.0
description: Heal command with GUI support.
author: flamexmystix
commands:
  heal:
    description: Heal yourself or other players.
    usage: /heal [player|gui]
    permission: healplus.self
permissions:
  healplus.self:
    description: Allows using /heal on yourself.
    default: op
  healplus.others:
    description: Allows healing other players.
    default: op

